# SPDX-License-Identifier: AGPL-3.0-or-later
"""add forum_crawl_cursor

Revision ID: 0002_forum_crawl_cursor
Revises: 0001_baseline
Create Date: 2026-09-30

Additive: the first post-baseline table (per-category forum backfill page
cursor). Multi-database revision; only the main DB changes, audit is a no-op.
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "0002_forum_crawl_cursor"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str) -> None:
    globals()[f"downgrade_{engine_name}"]()


def upgrade_main() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forum_crawl_cursor",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("category_platform_groupid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("next_page", sa.Integer(), nullable=False),
        sa.Column("backfill_complete", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "category_platform_groupid", name="uq_forum_crawl_cursor"),
    )
    with op.batch_alter_table("forum_crawl_cursor", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forum_crawl_cursor_category_platform_groupid"),
            ["category_platform_groupid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_forum_crawl_cursor_source_id"), ["source_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade_main() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forum_crawl_cursor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forum_crawl_cursor_source_id"))
        batch_op.drop_index(batch_op.f("ix_forum_crawl_cursor_category_platform_groupid"))

    op.drop_table("forum_crawl_cursor")
    # ### end Alembic commands ###


def upgrade_audit() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
